import type { MetadataRoute } from 'next';
import { APP_NAME, THEME_COLOR } from '@/brand/tokens';

/**
 * PWA-lite: a manifest so "Add to Home Screen" works, and nothing else.
 *
 * No service worker, no offline support, no push — all explicitly out of
 * scope for this phase (see PHASE12_PROMPT.md's "explicitly OUT of scope"
 * list; push rides WhatsApp for partners today, and a service worker with no
 * offline strategy behind it is just a caching bug waiting to happen). This
 * file alone is enough for Chrome/Android's install prompt, which is the
 * whole ask: a WhatsApp-forwarded link should be pinnable to a home screen.
 *
 * Icons are flat placeholder squares (`public/icons/`, generated by
 * `scripts` — see apps/web/README.md) in the brand-tokens primary colour.
 * Real, licensed brand artwork (including a maskable variant with proper
 * safe-zone padding) is a pre-launch task, not a foundation one — swap the
 * files in `public/icons/` and this manifest needs no changes.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: APP_NAME,
    short_name: APP_NAME,
    description: 'Book verified local technicians — electricians, plumbers and more.',
    // No `hi`/`en` variant here: web manifests do not support per-locale
    // metadata, and the OS reads this once at install time regardless of
    // which locale the page was installed from.
    start_url: '/',
    scope: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: THEME_COLOR,
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    ],
  };
}
