-- Initial schema — one migration, squashed from the 14 that built Phases 1-12.
--
-- ## Why this is a squash and not a fifteenth migration
--
-- The old migration #1 began `CREATE EXTENSION postgis`, and the production
-- host cannot provide it: its PostgreSQL is aaPanel's source-compiled build at
-- /www/server/pgsql, whose extension directory contains neither `postgis` nor
-- `btree_gist`. (`apt install postgresql-16-postgis-3` installs into
-- /usr/share/postgresql/, which that server never reads — it appears to succeed
-- and changes nothing.) So every deploy would have failed on statement one,
-- and a migration that converted geography columns *afterwards* could never run
-- either. The history had to collapse.
--
-- Squashing was safe here because no database had been deployed yet: the target
-- had zero tables and no `_prisma_migrations` row. The 14 original files remain
-- in git history.
--
-- ## What changed from those 14
--
--   1. `geography(Point, 4326)` columns became plain doubles:
--        addresses.location          -> addresses.lat / addresses.lng
--        provider_profiles.base_location -> base_lat / base_lng
--      Distance is computed with haversine SQL generated by
--      `src/core/geo-sql.ts`, which is also where the PostGIS path lives if a
--      future host supports it. Accuracy cost: ~0.3% (about 15 m over 5 km).
--
--   2. The two GiST spatial indexes are gone. Radius queries pre-filter with a
--      lat/lng bounding box, which ordinary B-tree indexes DO accelerate, then
--      compute exact distance on the survivors. At one city this is fast; it
--      would not be at national scale.
--
--   3. The double-booking guard changed shape. It was:
--        EXCLUDE USING gist (provider_id WITH =, time_range WITH &&)
--          WHERE (status IN ('held','booked'))
--      which needs btree_gist. It is now a partial UNIQUE INDEX on
--      (provider_id, starts_at) with the same WHERE clause, and the derived
--      `time_range` column and its trigger are gone with it.
--
--      Equivalent here because slots are generated on a fixed grid from
--      availability templates (`slot-plan.ts`: dayStart + n * incrementMinutes),
--      so two live slots for one provider can only collide on an identical
--      starts_at. It does NOT catch arbitrary overlapping ranges — if slots ever
--      become caller-timed, the exclusion constraint must come back, and that
--      needs btree_gist.
--
--   4. Staff moved out of `users` into `admin_users` (email + password, no
--      phone, no OTP), and `audit_logs` gained `actor_admin_id`.
--
-- Everything else — every table, trigger, append-only guard, CHECK constraint,
-- partial index and view — is carried over unchanged.

-- pg_trgm backs the Hinglish fuzzy-match indexes further down. It is present on
-- the host; postgis and btree_gist are not, hence the changes above.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "role" AS ENUM ('customer', 'technician', 'ops', 'admin');

-- CreateEnum
CREATE TYPE "user_status" AS ENUM ('active', 'blocked');

-- CreateEnum
CREATE TYPE "admin_role" AS ENUM ('admin', 'subadmin');

-- CreateEnum
CREATE TYPE "admin_status" AS ENUM ('active', 'disabled');

-- CreateEnum
CREATE TYPE "language" AS ENUM ('hi', 'en');

-- CreateEnum
CREATE TYPE "address_label" AS ENUM ('home', 'shop', 'other');

-- CreateEnum
CREATE TYPE "price_type" AS ENUM ('fixed', 'starting_from', 'inspection_based');

-- CreateEnum
CREATE TYPE "provider_document_type" AS ENUM ('id_proof', 'certificate', 'photo', 'other');

-- CreateEnum
CREATE TYPE "provider_document_status" AS ENUM ('awaiting_upload', 'uploaded');

-- CreateEnum
CREATE TYPE "suspension_reason" AS ENUM ('auto_low_trust', 'auto_repeat_cancellation', 'complaint_severe', 'safety_pending_review', 'ops_manual');

-- CreateEnum
CREATE TYPE "verification_status" AS ENUM ('submitted', 'in_review', 'needs_info', 'passed', 'failed');

-- CreateEnum
CREATE TYPE "verification_event_type" AS ENUM ('submitted', 'moved_to_review', 'info_requested', 'info_provided', 'passed', 'failed', 'adapter_result_received');

-- CreateEnum
CREATE TYPE "verification_actor_type" AS ENUM ('provider', 'ops', 'system');

-- CreateEnum
CREATE TYPE "badge" AS ENUM ('NONE', 'VERIFIED', 'SILVER', 'GOLD');

-- CreateEnum
CREATE TYPE "slot_status" AS ENUM ('open', 'held', 'booked', 'blocked');

-- CreateEnum
CREATE TYPE "booking_status" AS ENUM ('REQUESTED', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'WORK_DONE', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_PROVIDER', 'CLOSED_QUOTE_DECLINED');

-- CreateEnum
CREATE TYPE "booking_event_type" AS ENUM ('requested', 'accepted', 'rejected', 'expired', 'en_route', 'arrived', 'work_started', 'work_done', 'cancelled_by_customer', 'cancelled_by_provider', 'otp_failed', 'otp_locked', 'quote_sent', 'quote_withdrawn', 'quote_approved', 'quote_rejected', 'work_declined', 'complaint_opened', 'complaint_in_review', 'complaint_resolved', 'complaint_dismissed');

-- CreateEnum
CREATE TYPE "booking_actor_type" AS ENUM ('customer', 'provider', 'system', 'ops');

-- CreateEnum
CREATE TYPE "quotation_status" AS ENUM ('sent', 'approved', 'rejected', 'superseded', 'withdrawn');

-- CreateEnum
CREATE TYPE "quotation_item_kind" AS ENUM ('part', 'labour_extra');

-- CreateEnum
CREATE TYPE "review_direction" AS ENUM ('customer_to_provider', 'provider_to_customer');

-- CreateEnum
CREATE TYPE "review_status" AS ENUM ('published', 'hidden');

-- CreateEnum
CREATE TYPE "complaint_category" AS ENUM ('overcharge', 'no_show', 'quality', 'behavior', 'cash_dispute', 'safety', 'other');

-- CreateEnum
CREATE TYPE "complaint_status" AS ENUM ('open', 'in_review', 'resolved', 'dismissed');

-- CreateEnum
CREATE TYPE "complaint_severity" AS ENUM ('minor', 'major', 'severe');

-- CreateEnum
CREATE TYPE "account_type" AS ENUM ('gateway_cash', 'provider_payable', 'provider_dues', 'platform_revenue', 'refunds_payable');

-- CreateEnum
CREATE TYPE "account_owner_type" AS ENUM ('platform', 'provider', 'customer');

-- CreateEnum
CREATE TYPE "ledger_journal_type" AS ENUM ('payment_captured', 'cash_collected', 'refund', 'payout', 'dues_settled', 'adjustment');

-- CreateEnum
CREATE TYPE "ledger_direction" AS ENUM ('debit', 'credit');

-- CreateEnum
CREATE TYPE "payment_purpose" AS ENUM ('final_bill', 'visit_fee_upfront');

-- CreateEnum
CREATE TYPE "payment_method" AS ENUM ('online', 'cash');

-- CreateEnum
CREATE TYPE "payment_gateway_name" AS ENUM ('fake', 'razorpay');

-- CreateEnum
CREATE TYPE "payment_status" AS ENUM ('created', 'captured', 'failed', 'refunded', 'partially_refunded');

-- CreateEnum
CREATE TYPE "refund_status" AS ENUM ('created', 'processed', 'failed');

-- CreateEnum
CREATE TYPE "payout_batch_status" AS ENUM ('draft', 'processing', 'completed');

-- CreateEnum
CREATE TYPE "payout_status" AS ENUM ('pending', 'paid', 'failed');

-- CreateEnum
CREATE TYPE "notification_channel" AS ENUM ('in_app', 'whatsapp', 'sms');

-- CreateEnum
CREATE TYPE "notification_criticality" AS ENUM ('critical', 'standard');

-- CreateEnum
CREATE TYPE "notification_delivery_status" AS ENUM ('queued', 'sent', 'failed', 'suppressed_quiet_hours');

-- CreateTable
CREATE TABLE "cities" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "state" VARCHAR(120) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "require_entry_approval" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "phone" VARCHAR(16) NOT NULL,
    "name" VARCHAR(120),
    "status" "user_status" NOT NULL DEFAULT 'active',
    "default_city_id" INTEGER,
    "preferred_language" "language" NOT NULL DEFAULT 'hi',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "admin_users" (
    "id" UUID NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password_hash" VARCHAR(400) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "role" "admin_role" NOT NULL,
    "status" "admin_status" NOT NULL DEFAULT 'active',
    "created_by_id" UUID,
    "last_login_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "admin_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_roles" (
    "user_id" UUID NOT NULL,
    "role" "role" NOT NULL,
    "granted_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_roles_pkey" PRIMARY KEY ("user_id","role")
);

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token_hash" CHAR(64) NOT NULL,
    "device_id" VARCHAR(128) NOT NULL,
    "device_info" VARCHAR(512),
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "revoked_at" TIMESTAMPTZ(3),
    "replaced_by_token_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "categories" (
    "id" SERIAL NOT NULL,
    "city_id" INTEGER NOT NULL,
    "parent_id" INTEGER,
    "name_key" VARCHAR(120) NOT NULL,
    "slug" VARCHAR(120) NOT NULL,
    "icon" VARCHAR(64),
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "hinglish_synonyms" (
    "id" SERIAL NOT NULL,
    "term" VARCHAR(120) NOT NULL,
    "category_id" INTEGER NOT NULL,
    "weight" INTEGER NOT NULL DEFAULT 1,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "hinglish_synonyms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_profiles" (
    "user_id" UUID NOT NULL,
    "display_name" VARCHAR(120),
    "email" VARCHAR(255),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "customer_profiles_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "addresses" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "label" "address_label" NOT NULL DEFAULT 'other',
    "label_text" VARCHAR(60),
    "address_text" VARCHAR(500) NOT NULL,
    "landmark" VARCHAR(200),
    "city_id" INTEGER NOT NULL,
    "lat" DOUBLE PRECISION NOT NULL,
    "lng" DOUBLE PRECISION NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "addresses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "provider_profiles" (
    "user_id" UUID NOT NULL,
    "display_name" VARCHAR(120),
    "bio" VARCHAR(1000),
    "years_experience" INTEGER,
    "city_id" INTEGER NOT NULL,
    "base_lat" DOUBLE PRECISION,
    "base_lng" DOUBLE PRECISION,
    "service_radius_km" INTEGER NOT NULL DEFAULT 5,
    "completeness_score" INTEGER NOT NULL DEFAULT 0,
    "is_listed" BOOLEAN NOT NULL DEFAULT false,
    "assisted_onboarding" BOOLEAN NOT NULL DEFAULT false,
    "suspended_until" TIMESTAMPTZ(3),
    "suspended_at" TIMESTAMPTZ(3),
    "suspension_reason" "suspension_reason",
    "entry_approved_at" TIMESTAMPTZ(3),
    "entry_approved_by" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "provider_profiles_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "provider_skills" (
    "provider_id" UUID NOT NULL,
    "category_id" INTEGER NOT NULL,
    "experience_note" VARCHAR(300),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "provider_skills_pkey" PRIMARY KEY ("provider_id","category_id")
);

-- CreateTable
CREATE TABLE "provider_price_cards" (
    "id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "category_id" INTEGER NOT NULL,
    "title" VARCHAR(120) NOT NULL,
    "price_type" "price_type" NOT NULL,
    "amount_paise" INTEGER,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "provider_price_cards_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "provider_availability_templates" (
    "id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "day_of_week" SMALLINT NOT NULL,
    "start_minute" SMALLINT NOT NULL,
    "end_minute" SMALLINT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "provider_availability_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "provider_documents" (
    "id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "doc_type" "provider_document_type" NOT NULL,
    "storage_key" VARCHAR(300) NOT NULL,
    "status" "provider_document_status" NOT NULL DEFAULT 'awaiting_upload',
    "content_type" VARCHAR(120) NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "uploaded_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "provider_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification_cases" (
    "id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "level" SMALLINT NOT NULL,
    "status" "verification_status" NOT NULL DEFAULT 'submitted',
    "opened_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "closed_at" TIMESTAMPTZ(3),
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "verification_cases_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification_events" (
    "id" UUID NOT NULL,
    "case_id" UUID NOT NULL,
    "event_type" "verification_event_type" NOT NULL,
    "actor_type" "verification_actor_type" NOT NULL,
    "actor_user_id" UUID,
    "notes" VARCHAR(2000),
    "payload" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verification_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "provider_verification_summaries" (
    "provider_id" UUID NOT NULL,
    "levels_passed" INTEGER[],
    "badge" "badge" NOT NULL DEFAULT 'NONE',
    "badge_since" TIMESTAMPTZ(3),
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "provider_verification_summaries_pkey" PRIMARY KEY ("provider_id")
);

-- CreateTable
CREATE TABLE "slots" (
    "id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "starts_at" TIMESTAMPTZ(3) NOT NULL,
    "ends_at" TIMESTAMPTZ(3) NOT NULL,
    "status" "slot_status" NOT NULL DEFAULT 'open',
    "source_template_id" UUID,
    "booking_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "slots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bookings" (
    "id" UUID NOT NULL,
    "customer_id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "category_id" INTEGER NOT NULL,
    "price_card_id" UUID,
    "address_id" UUID,
    "address_snapshot" JSONB NOT NULL,
    "starts_at" TIMESTAMPTZ(3) NOT NULL,
    "ends_at" TIMESTAMPTZ(3) NOT NULL,
    "problem_note" VARCHAR(500),
    "visit_fee_paise" INTEGER NOT NULL,
    "status" "booking_status" NOT NULL DEFAULT 'REQUESTED',
    "price_card_amount_paise" INTEGER,
    "price_card_type" "price_type",
    "payable_paise" INTEGER,
    "payable_breakdown" JSONB,
    "rescheduled_from_booking_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "bookings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "booking_events" (
    "id" UUID NOT NULL,
    "booking_id" UUID NOT NULL,
    "event_type" "booking_event_type" NOT NULL,
    "actor_type" "booking_actor_type" NOT NULL,
    "actor_user_id" UUID,
    "payload" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "booking_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "fee_config" (
    "id" UUID NOT NULL,
    "city_id" INTEGER NOT NULL,
    "category_id" INTEGER,
    "visit_fee_paise" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "effective_from" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "fee_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "quotations" (
    "id" UUID NOT NULL,
    "booking_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "status" "quotation_status" NOT NULL DEFAULT 'sent',
    "labour_paise" INTEGER NOT NULL,
    "parts_total_paise" INTEGER NOT NULL,
    "total_paise" INTEGER NOT NULL,
    "note" VARCHAR(500),
    "created_by" UUID NOT NULL,
    "decided_at" TIMESTAMPTZ(3),
    "decision_note" VARCHAR(200),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "quotations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "quotation_items" (
    "id" UUID NOT NULL,
    "quotation_id" UUID NOT NULL,
    "kind" "quotation_item_kind" NOT NULL,
    "description" VARCHAR(120) NOT NULL,
    "qty" INTEGER NOT NULL,
    "unit_paise" INTEGER NOT NULL,
    "line_total_paise" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "quotation_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reviews" (
    "id" UUID NOT NULL,
    "booking_id" UUID NOT NULL,
    "direction" "review_direction" NOT NULL,
    "author_user_id" UUID NOT NULL,
    "subject_user_id" UUID NOT NULL,
    "stars" INTEGER NOT NULL,
    "tags" TEXT[],
    "text" VARCHAR(500),
    "status" "review_status" NOT NULL DEFAULT 'published',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "review_reports" (
    "id" UUID NOT NULL,
    "review_id" UUID NOT NULL,
    "reporter_user_id" UUID NOT NULL,
    "reason" VARCHAR(300) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "review_reports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "complaints" (
    "id" UUID NOT NULL,
    "booking_id" UUID NOT NULL,
    "raised_by_user_id" UUID NOT NULL,
    "against_user_id" UUID NOT NULL,
    "category" "complaint_category" NOT NULL,
    "description" VARCHAR(1000) NOT NULL,
    "status" "complaint_status" NOT NULL DEFAULT 'open',
    "resolution_note" VARCHAR(1000),
    "severity_on_resolution" "complaint_severity",
    "resolved_by_user_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "resolved_at" TIMESTAMPTZ(3),

    CONSTRAINT "complaints_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "trust_score_snapshots" (
    "id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "score" INTEGER NOT NULL,
    "components" JSONB NOT NULL,
    "badge_band_after" "badge" NOT NULL,
    "trigger_topic" VARCHAR(120) NOT NULL,
    "trigger_aggregate_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "trust_score_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "accounts" (
    "id" UUID NOT NULL,
    "account_type" "account_type" NOT NULL,
    "owner_type" "account_owner_type" NOT NULL,
    "owner_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ledger_journals" (
    "id" UUID NOT NULL,
    "journal_type" "ledger_journal_type" NOT NULL,
    "booking_id" UUID,
    "payment_id" UUID,
    "memo" VARCHAR(500),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ledger_journals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ledger_entries" (
    "id" UUID NOT NULL,
    "journal_id" UUID NOT NULL,
    "account_id" UUID NOT NULL,
    "direction" "ledger_direction" NOT NULL,
    "amount_paise" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ledger_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "commission_config" (
    "id" UUID NOT NULL,
    "city_id" INTEGER NOT NULL,
    "category_id" INTEGER,
    "rate_bps" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "effective_from" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "commission_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payments" (
    "id" UUID NOT NULL,
    "booking_id" UUID,
    "purpose" "payment_purpose" NOT NULL,
    "method" "payment_method" NOT NULL,
    "amount_paise" INTEGER NOT NULL,
    "commission_bps_snapshot" INTEGER NOT NULL,
    "gateway" "payment_gateway_name",
    "gateway_order_id" VARCHAR(120),
    "gateway_payment_id" VARCHAR(120),
    "status" "payment_status" NOT NULL DEFAULT 'created',
    "checkout_verified_at" TIMESTAMPTZ(3),
    "captured_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refunds" (
    "id" UUID NOT NULL,
    "payment_id" UUID NOT NULL,
    "amount_paise" INTEGER NOT NULL,
    "gateway_refund_id" VARCHAR(120),
    "status" "refund_status" NOT NULL DEFAULT 'created',
    "reason" VARCHAR(300),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "refunds_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_events" (
    "id" UUID NOT NULL,
    "gateway" VARCHAR(40) NOT NULL,
    "gateway_event_id" VARCHAR(200) NOT NULL,
    "event_type" VARCHAR(120) NOT NULL,
    "payload" JSONB NOT NULL,
    "received_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processed_at" TIMESTAMPTZ(3),
    "processing_error" VARCHAR(1000),

    CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payout_batches" (
    "id" UUID NOT NULL,
    "status" "payout_batch_status" NOT NULL DEFAULT 'draft',
    "created_by" UUID,
    "window_end" TIMESTAMPTZ(3) NOT NULL,
    "total_paise" INTEGER NOT NULL,
    "payout_count" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(3),

    CONSTRAINT "payout_batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payouts" (
    "id" UUID NOT NULL,
    "batch_id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "amount_paise" INTEGER NOT NULL,
    "status" "payout_status" NOT NULL DEFAULT 'pending',
    "utr_ref" VARCHAR(60),
    "paid_at" TIMESTAMPTZ(3),
    "failure_note" VARCHAR(300),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "payouts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "outbox" (
    "id" UUID NOT NULL,
    "topic" VARCHAR(120) NOT NULL,
    "aggregate_type" VARCHAR(60) NOT NULL,
    "aggregate_id" UUID NOT NULL,
    "payload" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processed_at" TIMESTAMPTZ(3),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "next_attempt_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_error" VARCHAR(2000),

    CONSTRAINT "outbox_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "provider_stats" (
    "provider_id" UUID NOT NULL,
    "accepted_count" INTEGER NOT NULL DEFAULT 0,
    "rejected_count" INTEGER NOT NULL DEFAULT 0,
    "expired_count" INTEGER NOT NULL DEFAULT 0,
    "cancelled_by_provider_count" INTEGER NOT NULL DEFAULT 0,
    "acceptance_rate" DOUBLE PRECISION,
    "window_days" INTEGER NOT NULL DEFAULT 30,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "avg_stars" DOUBLE PRECISION,
    "review_count" INTEGER NOT NULL DEFAULT 0,
    "tag_counts" JSONB,
    "settled_jobs_count" INTEGER NOT NULL DEFAULT 0,
    "last_settled_at" TIMESTAMPTZ(3),
    "complaints_minor_count" INTEGER NOT NULL DEFAULT 0,
    "complaints_major_count" INTEGER NOT NULL DEFAULT 0,
    "complaints_severe_count" INTEGER NOT NULL DEFAULT 0,
    "trust_score" INTEGER,
    "trust_score_updated" TIMESTAMPTZ(3),

    CONSTRAINT "provider_stats_pkey" PRIMARY KEY ("provider_id")
);

-- CreateTable
CREATE TABLE "kyc_access_logs" (
    "id" UUID NOT NULL,
    "provider_id" UUID NOT NULL,
    "actor_user_id" UUID NOT NULL,
    "case_id" UUID,
    "document_ids" TEXT[],
    "action" VARCHAR(60) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kyc_access_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" UUID NOT NULL,
    "actor_user_id" UUID,
    "actor_admin_id" UUID,
    "action" VARCHAR(80) NOT NULL,
    "target_type" VARCHAR(40) NOT NULL,
    "target_id" VARCHAR(120),
    "payload" JSONB NOT NULL,
    "ip" VARCHAR(64),
    "request_id" VARCHAR(140),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "topic" VARCHAR(120) NOT NULL,
    "aggregate_id" UUID NOT NULL,
    "title_key" VARCHAR(160) NOT NULL,
    "body_key" VARCHAR(160) NOT NULL,
    "params" JSONB NOT NULL,
    "deep_link" VARCHAR(200),
    "criticality" "notification_criticality" NOT NULL,
    "read_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_deliveries" (
    "id" UUID NOT NULL,
    "notification_id" UUID NOT NULL,
    "topic" VARCHAR(120) NOT NULL,
    "aggregate_id" UUID NOT NULL,
    "recipient_user_id" UUID NOT NULL,
    "channel" "notification_channel" NOT NULL,
    "transport" VARCHAR(40) NOT NULL,
    "status" "notification_delivery_status" NOT NULL DEFAULT 'queued',
    "transport_ref" VARCHAR(200),
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_error" VARCHAR(1000),
    "scheduled_for" TIMESTAMPTZ(3),
    "sent_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "notification_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "cities_is_active_idx" ON "cities"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "cities_name_state_key" ON "cities"("name", "state");

-- CreateIndex
CREATE UNIQUE INDEX "users_phone_key" ON "users"("phone");

-- CreateIndex
CREATE INDEX "users_status_idx" ON "users"("status");

-- CreateIndex
-- NOTE: the unique index on admin_users.email is created further down as a
-- case-insensitive one over LOWER("email"). A plain unique index here would
-- let Admin@x.com and admin@x.com become two accounts.

-- CreateIndex
CREATE INDEX "admin_users_status_idx" ON "admin_users"("status");

-- CreateIndex
CREATE INDEX "user_roles_role_idx" ON "user_roles"("role");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_replaced_by_token_id_key" ON "refresh_tokens"("replaced_by_token_id");

-- CreateIndex
CREATE INDEX "refresh_tokens_user_id_device_id_idx" ON "refresh_tokens"("user_id", "device_id");

-- CreateIndex
CREATE INDEX "refresh_tokens_expires_at_idx" ON "refresh_tokens"("expires_at");

-- CreateIndex
CREATE INDEX "categories_city_id_is_active_idx" ON "categories"("city_id", "is_active");

-- CreateIndex
CREATE INDEX "categories_parent_id_idx" ON "categories"("parent_id");

-- CreateIndex
CREATE UNIQUE INDEX "categories_city_id_slug_key" ON "categories"("city_id", "slug");

-- CreateIndex
CREATE INDEX "hinglish_synonyms_category_id_idx" ON "hinglish_synonyms"("category_id");

-- CreateIndex
CREATE UNIQUE INDEX "hinglish_synonyms_term_category_id_key" ON "hinglish_synonyms"("term", "category_id");

-- CreateIndex
CREATE INDEX "addresses_user_id_idx" ON "addresses"("user_id");

-- CreateIndex
CREATE INDEX "provider_profiles_city_id_is_listed_idx" ON "provider_profiles"("city_id", "is_listed");

-- CreateIndex
CREATE INDEX "provider_profiles_suspended_until_idx" ON "provider_profiles"("suspended_until");

-- CreateIndex
CREATE INDEX "provider_skills_category_id_idx" ON "provider_skills"("category_id");

-- CreateIndex
CREATE INDEX "provider_price_cards_provider_id_is_active_idx" ON "provider_price_cards"("provider_id", "is_active");

-- CreateIndex
CREATE INDEX "provider_availability_templates_provider_id_day_of_week_idx" ON "provider_availability_templates"("provider_id", "day_of_week");

-- CreateIndex
CREATE UNIQUE INDEX "provider_documents_storage_key_key" ON "provider_documents"("storage_key");

-- CreateIndex
CREATE INDEX "provider_documents_provider_id_doc_type_idx" ON "provider_documents"("provider_id", "doc_type");

-- CreateIndex
CREATE INDEX "provider_documents_provider_id_status_idx" ON "provider_documents"("provider_id", "status");

-- CreateIndex
CREATE INDEX "verification_cases_provider_id_level_idx" ON "verification_cases"("provider_id", "level");

-- CreateIndex
CREATE INDEX "verification_cases_status_opened_at_idx" ON "verification_cases"("status", "opened_at");

-- CreateIndex
CREATE INDEX "verification_events_case_id_created_at_idx" ON "verification_events"("case_id", "created_at");

-- CreateIndex
CREATE INDEX "provider_verification_summaries_badge_idx" ON "provider_verification_summaries"("badge");

-- CreateIndex
CREATE UNIQUE INDEX "slots_booking_id_key" ON "slots"("booking_id");

-- CreateIndex
CREATE INDEX "slots_provider_id_starts_at_idx" ON "slots"("provider_id", "starts_at");

-- CreateIndex
CREATE INDEX "slots_status_starts_at_idx" ON "slots"("status", "starts_at");

-- CreateIndex
CREATE INDEX "bookings_customer_id_created_at_idx" ON "bookings"("customer_id", "created_at");

-- CreateIndex
CREATE INDEX "bookings_provider_id_created_at_idx" ON "bookings"("provider_id", "created_at");

-- CreateIndex
CREATE INDEX "bookings_status_created_at_idx" ON "bookings"("status", "created_at");

-- CreateIndex
CREATE INDEX "booking_events_booking_id_created_at_idx" ON "booking_events"("booking_id", "created_at");

-- CreateIndex
CREATE INDEX "fee_config_city_id_is_active_effective_from_idx" ON "fee_config"("city_id", "is_active", "effective_from");

-- CreateIndex
CREATE INDEX "quotations_booking_id_created_at_idx" ON "quotations"("booking_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "quotations_booking_id_version_key" ON "quotations"("booking_id", "version");

-- CreateIndex
CREATE INDEX "quotation_items_quotation_id_idx" ON "quotation_items"("quotation_id");

-- CreateIndex
CREATE INDEX "reviews_subject_user_id_status_created_at_idx" ON "reviews"("subject_user_id", "status", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "reviews_booking_id_direction_key" ON "reviews"("booking_id", "direction");

-- CreateIndex
CREATE INDEX "review_reports_review_id_idx" ON "review_reports"("review_id");

-- CreateIndex
CREATE UNIQUE INDEX "review_reports_review_id_reporter_user_id_key" ON "review_reports"("review_id", "reporter_user_id");

-- CreateIndex
CREATE INDEX "complaints_against_user_id_status_idx" ON "complaints"("against_user_id", "status");

-- CreateIndex
CREATE INDEX "complaints_status_created_at_idx" ON "complaints"("status", "created_at");

-- CreateIndex
CREATE INDEX "complaints_booking_id_idx" ON "complaints"("booking_id");

-- CreateIndex
CREATE INDEX "trust_score_snapshots_provider_id_created_at_idx" ON "trust_score_snapshots"("provider_id", "created_at");

-- CreateIndex
CREATE INDEX "ledger_journals_journal_type_created_at_idx" ON "ledger_journals"("journal_type", "created_at");

-- CreateIndex
CREATE INDEX "ledger_journals_booking_id_idx" ON "ledger_journals"("booking_id");

-- CreateIndex
CREATE INDEX "ledger_entries_account_id_created_at_idx" ON "ledger_entries"("account_id", "created_at");

-- CreateIndex
CREATE INDEX "ledger_entries_journal_id_idx" ON "ledger_entries"("journal_id");

-- CreateIndex
CREATE INDEX "commission_config_city_id_is_active_effective_from_idx" ON "commission_config"("city_id", "is_active", "effective_from");

-- CreateIndex
CREATE INDEX "payments_booking_id_idx" ON "payments"("booking_id");

-- CreateIndex
CREATE INDEX "payments_status_created_at_idx" ON "payments"("status", "created_at");

-- CreateIndex
CREATE INDEX "refunds_payment_id_idx" ON "refunds"("payment_id");

-- CreateIndex
CREATE UNIQUE INDEX "webhook_events_gateway_event_id_key" ON "webhook_events"("gateway_event_id");

-- CreateIndex
CREATE INDEX "webhook_events_processed_at_received_at_idx" ON "webhook_events"("processed_at", "received_at");

-- CreateIndex
CREATE INDEX "webhook_events_event_type_idx" ON "webhook_events"("event_type");

-- CreateIndex
CREATE INDEX "payout_batches_status_created_at_idx" ON "payout_batches"("status", "created_at");

-- CreateIndex
CREATE INDEX "payouts_provider_id_created_at_idx" ON "payouts"("provider_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "payouts_batch_id_provider_id_key" ON "payouts"("batch_id", "provider_id");

-- CreateIndex
CREATE INDEX "outbox_processed_at_next_attempt_at_idx" ON "outbox"("processed_at", "next_attempt_at");

-- CreateIndex
CREATE INDEX "outbox_aggregate_type_aggregate_id_idx" ON "outbox"("aggregate_type", "aggregate_id");

-- CreateIndex
CREATE INDEX "kyc_access_logs_provider_id_created_at_idx" ON "kyc_access_logs"("provider_id", "created_at");

-- CreateIndex
CREATE INDEX "kyc_access_logs_actor_user_id_created_at_idx" ON "kyc_access_logs"("actor_user_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs"("created_at" DESC);

-- CreateIndex
CREATE INDEX "audit_logs_actor_user_id_created_at_idx" ON "audit_logs"("actor_user_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_logs_actor_admin_id_created_at_idx" ON "audit_logs"("actor_admin_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_logs_action_created_at_idx" ON "audit_logs"("action", "created_at");

-- CreateIndex
CREATE INDEX "audit_logs_target_type_target_id_idx" ON "audit_logs"("target_type", "target_id");

-- CreateIndex
CREATE INDEX "notifications_user_id_created_at_idx" ON "notifications"("user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "notifications_user_id_read_at_idx" ON "notifications"("user_id", "read_at");

-- CreateIndex
CREATE INDEX "notification_deliveries_status_scheduled_for_idx" ON "notification_deliveries"("status", "scheduled_for");

-- CreateIndex
CREATE INDEX "notification_deliveries_notification_id_idx" ON "notification_deliveries"("notification_id");

-- CreateIndex
CREATE UNIQUE INDEX "notification_deliveries_topic_aggregate_id_recipient_user_i_key" ON "notification_deliveries"("topic", "aggregate_id", "recipient_user_id", "channel");

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_default_city_id_fkey" FOREIGN KEY ("default_city_id") REFERENCES "cities"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "admin_users" ADD CONSTRAINT "admin_users_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_replaced_by_token_id_fkey" FOREIGN KEY ("replaced_by_token_id") REFERENCES "refresh_tokens"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "categories" ADD CONSTRAINT "categories_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "hinglish_synonyms" ADD CONSTRAINT "hinglish_synonyms_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_profiles" ADD CONSTRAINT "customer_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_profiles" ADD CONSTRAINT "provider_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_profiles" ADD CONSTRAINT "provider_profiles_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_skills" ADD CONSTRAINT "provider_skills_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_skills" ADD CONSTRAINT "provider_skills_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_price_cards" ADD CONSTRAINT "provider_price_cards_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_price_cards" ADD CONSTRAINT "provider_price_cards_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_availability_templates" ADD CONSTRAINT "provider_availability_templates_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_documents" ADD CONSTRAINT "provider_documents_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_cases" ADD CONSTRAINT "verification_cases_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "verification_events" ADD CONSTRAINT "verification_events_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "verification_cases"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_verification_summaries" ADD CONSTRAINT "provider_verification_summaries_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "slots" ADD CONSTRAINT "slots_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "slots" ADD CONSTRAINT "slots_source_template_id_fkey" FOREIGN KEY ("source_template_id") REFERENCES "provider_availability_templates"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "slots" ADD CONSTRAINT "slots_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_price_card_id_fkey" FOREIGN KEY ("price_card_id") REFERENCES "provider_price_cards"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_events" ADD CONSTRAINT "booking_events_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "fee_config" ADD CONSTRAINT "fee_config_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "fee_config" ADD CONSTRAINT "fee_config_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "quotations" ADD CONSTRAINT "quotations_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "quotations" ADD CONSTRAINT "quotations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "quotation_items" ADD CONSTRAINT "quotation_items_quotation_id_fkey" FOREIGN KEY ("quotation_id") REFERENCES "quotations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_subject_user_id_fkey" FOREIGN KEY ("subject_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_reports" ADD CONSTRAINT "review_reports_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "review_reports" ADD CONSTRAINT "review_reports_reporter_user_id_fkey" FOREIGN KEY ("reporter_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "complaints" ADD CONSTRAINT "complaints_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "complaints" ADD CONSTRAINT "complaints_raised_by_user_id_fkey" FOREIGN KEY ("raised_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "complaints" ADD CONSTRAINT "complaints_against_user_id_fkey" FOREIGN KEY ("against_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "complaints" ADD CONSTRAINT "complaints_resolved_by_user_id_fkey" FOREIGN KEY ("resolved_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "trust_score_snapshots" ADD CONSTRAINT "trust_score_snapshots_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ledger_journals" ADD CONSTRAINT "ledger_journals_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ledger_journals" ADD CONSTRAINT "ledger_journals_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_journal_id_fkey" FOREIGN KEY ("journal_id") REFERENCES "ledger_journals"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "commission_config" ADD CONSTRAINT "commission_config_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "commission_config" ADD CONSTRAINT "commission_config_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refunds" ADD CONSTRAINT "refunds_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "payout_batches"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "provider_stats" ADD CONSTRAINT "provider_stats_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider_profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_admin_id_fkey" FOREIGN KEY ("actor_admin_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_deliveries" ADD CONSTRAINT "notification_deliveries_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_deliveries" ADD CONSTRAINT "notification_deliveries_recipient_user_id_fkey" FOREIGN KEY ("recipient_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- Must be the first migration: everything geospatial later depends on it.

-- pg_trgm  : fuzzy text matching for provider/skill search
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- A partial index over exactly what search will filter on: listed providers in a city.
CREATE INDEX "provider_profiles_listed_city_idx" ON "provider_profiles" ("city_id") WHERE "is_listed" = true;

-- One default address per user, enforced by the database rather than by hoping
-- the service always clears the old default first.
CREATE UNIQUE INDEX "addresses_one_default_per_user_idx" ON "addresses" ("user_id") WHERE "is_default" = true;

-- The taxonomy is two levels deep: a category's parent must itself be a root.
-- This cannot be a CHECK (no subqueries), so it is a trigger.
CREATE OR REPLACE FUNCTION categories_enforce_two_levels() RETURNS trigger AS $$
BEGIN
  IF NEW.parent_id IS NOT NULL THEN
    IF (SELECT parent_id FROM categories WHERE id = NEW.parent_id) IS NOT NULL THEN
      RAISE EXCEPTION 'category tree is limited to two levels: parent % is not a root', NEW.parent_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER categories_two_levels_trigger
  BEFORE INSERT OR UPDATE ON "categories"
  FOR EACH ROW EXECUTE FUNCTION categories_enforce_two_levels();


-- At most one live case per (provider, level). A provider retries a failed level
-- by opening a NEW case; the closed one stays untouched forever, which is what
-- makes the history reconstructable.
CREATE UNIQUE INDEX "verification_cases_one_open_per_level_idx"
  ON "verification_cases" ("provider_id", "level")
  WHERE "status" NOT IN ('passed', 'failed');

-- Levels recorded as passed must be real levels, and each at most once.
--
-- The duplicate test lives in a function because a CHECK constraint may not
-- contain a subquery, and de-duplicating an array needs one. Immutable, so it is
-- safe to constrain on.
CREATE OR REPLACE FUNCTION int_array_is_distinct(arr integer[]) RETURNS boolean AS $$
  SELECT arr IS NULL
      OR cardinality(arr) = (SELECT count(DISTINCT value) FROM unnest(arr) AS value);
$$ LANGUAGE sql IMMUTABLE;

-- ---------------------------------------------------------------------------
-- The append-only guarantee.
--
-- "Why did this technician have a badge on the day of the incident?" is only
-- answerable if no row in the event log can ever be edited or quietly removed.
-- Application discipline is not enough — this is enforced by the database, so a
-- stray UPDATE from a migration, a console session or a future bug cannot
-- rewrite history.
--
-- UPDATE is refused unconditionally. DELETE is refused too, except when the
-- session explicitly sets `fixbridge.allow_kyc_purge = 'on'` — the deliberate
-- escape hatch for DPDP erasure (Phase 14) and for test fixture teardown, which
-- is also what lets the ON DELETE CASCADE from users work at all. Erasing a
-- person's data has to be possible; doing it by accident must not be.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION verification_events_append_only() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' AND coalesce(current_setting('fixbridge.allow_kyc_purge', true), '') = 'on' THEN
    RETURN OLD;
  END IF;

  RAISE EXCEPTION
    'verification_events is append-only: % is not permitted (id=%)',
    TG_OP,
    CASE TG_OP WHEN 'DELETE' THEN OLD.id ELSE NEW.id END
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER verification_events_no_update
  BEFORE UPDATE ON "verification_events"
  FOR EACH ROW EXECUTE FUNCTION verification_events_append_only();

CREATE TRIGGER verification_events_no_delete
  BEFORE DELETE ON "verification_events"
  FOR EACH ROW EXECUTE FUNCTION verification_events_append_only();


-- Trigram indexes for fuzzy matching. "moter jal gai" has to find
-- "motor jal gayi", and a customer typing on a phone will misspell things.
-- pg_trgm has been enabled since the first migration.
CREATE INDEX "hinglish_synonyms_term_trgm_idx"
  ON "hinglish_synonyms" USING GIN ("term" gin_trgm_ops);

-- Category slugs are searched the same way when no synonym matches.
CREATE INDEX "categories_slug_trgm_idx"
  ON "categories" USING GIN ("slug" gin_trgm_ops);

-- Availability lookups filter on day and window, not just provider.
CREATE INDEX "provider_availability_day_window_idx"
  ON "provider_availability_templates" ("day_of_week", "start_minute", "end_minute")
  WHERE "is_active" = true;


-- ===========================================================================
-- APPEND-ONLY BOOKING HISTORY
--
-- Identical discipline to verification_events, and for the same reason: "what
-- actually happened on this job" has to survive a dispute months later. UPDATE
-- is refused outright; DELETE only under the same explicit purge flag, which is
-- what lets ON DELETE CASCADE and DPDP erasure work at all.
-- ===========================================================================
CREATE OR REPLACE FUNCTION booking_events_append_only() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' AND coalesce(current_setting('fixbridge.allow_kyc_purge', true), '') = 'on' THEN
    RETURN OLD;
  END IF;

  RAISE EXCEPTION
    'booking_events is append-only: % is not permitted (id=%)',
    TG_OP,
    CASE TG_OP WHEN 'DELETE' THEN OLD.id ELSE NEW.id END
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER booking_events_no_update
  BEFORE UPDATE ON "booking_events"
  FOR EACH ROW EXECUTE FUNCTION booking_events_append_only();

CREATE TRIGGER booking_events_no_delete
  BEFORE DELETE ON "booking_events"
  FOR EACH ROW EXECUTE FUNCTION booking_events_append_only();

-- The dispatcher's hot query: unprocessed rows whose backoff has elapsed.
CREATE INDEX "outbox_pending_idx"
  ON "outbox" ("next_attempt_at", "created_at")
  WHERE "processed_at" IS NULL;

-- Search asks "does this provider have an open slot covering the window?" on
-- every availability-filtered query.
CREATE INDEX "slots_open_provider_window_idx"
  ON "slots" ("provider_id", "starts_at", "ends_at")
  WHERE "status" = 'open';


--   * a customer approving v1 while the provider sends v2 — the approval leaves
--     v1 live and the insert of v2 collides, so exactly one commits.
--
-- Application code narrows the window and turns the loss into a friendly 409.
-- This is the part that makes it impossible.
-- ===========================================================================
CREATE UNIQUE INDEX "quotations_one_live_per_booking_idx"
  ON "quotations" ("booking_id")
  WHERE ("status" IN ('sent', 'approved'));

-- ===========================================================================
-- IMMUTABILITY
--
-- The customer saw v1. v1 has to survive forever, exactly as it was shown —
-- that is the entire trust proposition of an itemised quote, and a convention
-- enforced only in TypeScript is not a proposition, it is a hope.
--
-- Quotations accept exactly one kind of UPDATE: leaving `sent`. Nothing else
-- about a quotation may ever change, and its items may not change at all.
-- ===========================================================================
CREATE OR REPLACE FUNCTION quotations_immutable() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF coalesce(current_setting('fixbridge.allow_kyc_purge', true), '') = 'on' THEN
      RETURN OLD;
    END IF;

    RAISE EXCEPTION 'quotations are append-only: DELETE is not permitted (id=%)', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Only a live quote can move, and only out of `sent`.
  IF OLD.status <> 'sent' THEN
    RAISE EXCEPTION 'quotation % is already %; it cannot be changed', OLD.id, OLD.status
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW.status = 'sent' THEN
    RAISE EXCEPTION 'quotation % cannot be updated while it stays sent', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Everything that made up the price is frozen.
  IF NEW.id <> OLD.id
     OR NEW.booking_id <> OLD.booking_id
     OR NEW.version <> OLD.version
     OR NEW.labour_paise <> OLD.labour_paise
     OR NEW.parts_total_paise <> OLD.parts_total_paise
     OR NEW.total_paise <> OLD.total_paise
     OR NEW.created_by <> OLD.created_by
     OR NEW.created_at <> OLD.created_at
     OR NEW.note IS DISTINCT FROM OLD.note
  THEN
    RAISE EXCEPTION 'quotation % is immutable: only status, decided_at and decision_note may change', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER quotations_immutable_update
  BEFORE UPDATE ON "quotations"
  FOR EACH ROW EXECUTE FUNCTION quotations_immutable();

CREATE TRIGGER quotations_immutable_delete
  BEFORE DELETE ON "quotations"
  FOR EACH ROW EXECUTE FUNCTION quotations_immutable();

CREATE OR REPLACE FUNCTION quotation_items_immutable() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' AND coalesce(current_setting('fixbridge.allow_kyc_purge', true), '') = 'on' THEN
    RETURN OLD;
  END IF;

  RAISE EXCEPTION
    'quotation_items is append-only: % is not permitted (id=%)',
    TG_OP,
    CASE TG_OP WHEN 'DELETE' THEN OLD.id ELSE NEW.id END
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER quotation_items_no_update
  BEFORE UPDATE ON "quotation_items"
  FOR EACH ROW EXECUTE FUNCTION quotation_items_immutable();

CREATE TRIGGER quotation_items_no_delete
  BEFORE DELETE ON "quotation_items"
  FOR EACH ROW EXECUTE FUNCTION quotation_items_immutable();


-- ===========================================================================
-- ONE LIVE PAYMENT PER BOOKING PER PURPOSE
--
-- `failed` is excluded so a customer whose UPI dropped can try again, and the
-- purpose is in the key so an upfront visit fee and a final bill can coexist on
-- the same booking when COLLECT_FEE_AT_BOOKING is on.
--
-- NULLS DISTINCT (the default) is deliberate here, unlike the accounts index
-- above: `booking_id` is nulled on erasure, and purged rows must not start
-- colliding with each other years later.
-- ===========================================================================
CREATE UNIQUE INDEX "payments_one_live_per_purpose_idx"
  ON "payments" ("booking_id", "purpose")
  WHERE ("status" <> 'failed');

-- ===========================================================================
-- ONE PAYMENT PER GATEWAY ORDER
--
-- A gateway order id identifies exactly one attempt to collect exactly one
-- bill, and the webhook handler finds a payment *by* that id — so two payments
-- sharing one would make the lookup ambiguous and the capture land on whichever
-- row happened to come back first. Enforcing it here means the question cannot
-- arise, rather than being answered correctly by convention.
-- ===========================================================================
CREATE UNIQUE INDEX "payments_gateway_order_id_key"
  ON "payments" ("gateway_order_id")
  WHERE ("gateway_order_id" IS NOT NULL);

-- Same reasoning for the refund's own id: the `refund.processed` webhook is
-- matched on it.
CREATE UNIQUE INDEX "refunds_gateway_refund_id_key"
  ON "refunds" ("gateway_refund_id")
  WHERE ("gateway_refund_id" IS NOT NULL);

-- ===========================================================================
-- LAW #1, ENFORCED
--
-- Every journal must balance: Σ debits = Σ credits.
--
-- This is a DEFERRED constraint trigger, which is the only way to express it:
-- entries are inserted one at a time, so any check that ran per-statement would
-- fail on the first row of a perfectly good journal. Deferring to COMMIT means
-- the assertion is made about the finished journal, and a transaction that
-- would leave the books unbalanced cannot commit at all.
--
-- Note what this is NOT: a validation in the service. The service validates too,
-- because a clear error beats a constraint violation — but if the two ever
-- disagree, this one wins, and money cannot go missing because somebody wrote a
-- new repository that forgot to call the old one.
-- ===========================================================================
CREATE OR REPLACE FUNCTION ledger_journal_must_balance(target UUID) RETURNS void AS $$
DECLARE
  debits BIGINT;
  credits BIGINT;
  lines INT;
BEGIN
  SELECT
    coalesce(sum("amount_paise") FILTER (WHERE "direction" = 'debit'), 0),
    coalesce(sum("amount_paise") FILTER (WHERE "direction" = 'credit'), 0),
    count(*)
  INTO debits, credits, lines
  FROM "ledger_entries"
  WHERE "journal_id" = target;

  -- A journal with one line cannot be double entry, whatever the arithmetic.
  IF lines < 2 THEN
    RAISE EXCEPTION 'ledger journal % has % entries; double entry needs at least two', target, lines
      USING ERRCODE = 'check_violation';
  END IF;

  IF debits <> credits THEN
    RAISE EXCEPTION 'ledger journal % does not balance: debits=% credits=%', target, debits, credits
      USING ERRCODE = 'check_violation';
  END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ledger_entry_balance_check() RETURNS trigger AS $$
BEGIN
  PERFORM ledger_journal_must_balance(NEW.journal_id);
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION ledger_journal_balance_check() RETURNS trigger AS $$
BEGIN
  PERFORM ledger_journal_must_balance(NEW.id);
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ===========================================================================
-- APPEND-ONLY, WITH NO ESCAPE HATCH
--
-- `verification_events` and `booking_events` allow DELETE under the DPDP purge
-- flag because they describe a person. Ledger rows describe money: they are not
-- personal data, they carry statutory retention, and an erasure request cuts the
-- link (`booking_id` → NULL) rather than the record. So there is no flag here,
-- and a correction is an `adjustment` journal — which is what double entry is
-- for in the first place.
-- ===========================================================================
CREATE OR REPLACE FUNCTION ledger_is_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION
    '% is immutable: % is never permitted — post an adjustment journal instead',
    TG_TABLE_NAME,
    TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

/**
 * The one permitted UPDATE on a journal: clearing a link for DPDP erasure.
 *
 * A journal is otherwise immutable — money that moved cannot be edited into
 * having moved differently; the correction is an adjustment journal. But
 * erasing a person must be able to detach their booking and payment from the
 * record without destroying the record itself, so `booking_id` and
 * `payment_id` may go from a value to NULL, and nothing else about a journal
 * may ever change.
 */
CREATE OR REPLACE FUNCTION ledger_journal_update_guard() RETURNS trigger AS $$
BEGIN
  IF NEW.id = OLD.id
     AND NEW.journal_type = OLD.journal_type
     AND NEW.created_at = OLD.created_at
     AND NEW.memo IS NOT DISTINCT FROM OLD.memo
     -- Only ever value -> NULL, never NULL -> value and never value -> other value.
     AND (NEW.booking_id IS NOT DISTINCT FROM OLD.booking_id OR NEW.booking_id IS NULL)
     AND (NEW.payment_id IS NOT DISTINCT FROM OLD.payment_id OR NEW.payment_id IS NULL)
  THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION
    'ledger_journals is immutable: only booking_id and payment_id may be cleared (erasure) — post an adjustment journal instead'
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "ledger_journals_no_update"
  BEFORE UPDATE ON "ledger_journals"
  FOR EACH ROW EXECUTE FUNCTION ledger_journal_update_guard();

CREATE TRIGGER "ledger_journals_no_delete"
  BEFORE DELETE ON "ledger_journals"
  FOR EACH ROW EXECUTE FUNCTION ledger_is_immutable();

CREATE TRIGGER "ledger_entries_no_update"
  BEFORE UPDATE ON "ledger_entries"
  FOR EACH ROW EXECUTE FUNCTION ledger_is_immutable();

CREATE TRIGGER "ledger_entries_no_delete"
  BEFORE DELETE ON "ledger_entries"
  FOR EACH ROW EXECUTE FUNCTION ledger_is_immutable();

-- ===========================================================================
-- BALANCES ARE VIEWS
--
-- Law #1 again, in the shape it takes at read time. There is no balance column
-- to drift, no cache to invalidate, and no way for a balance to be wrong that
-- does not involve the entries themselves being wrong.
--
-- Sign conventions, stated once:
--   asset      (gateway_cash, provider_dues)                debits − credits
--   liability  (provider_payable, refunds_payable)          credits − debits
--   revenue    (platform_revenue)                           credits − debits
-- ===========================================================================
CREATE OR REPLACE VIEW "account_balances" AS
SELECT
  a."id"           AS account_id,
  a."account_type" AS account_type,
  a."owner_type"   AS owner_type,
  a."owner_id"     AS owner_id,
  coalesce(sum(CASE WHEN e."direction" = 'debit' THEN e."amount_paise" ELSE 0 END), 0)::BIGINT  AS debits_paise,
  coalesce(sum(CASE WHEN e."direction" = 'credit' THEN e."amount_paise" ELSE 0 END), 0)::BIGINT AS credits_paise,
  -- Signed so that a positive number always means "this account holds value",
  -- whichever side of the books it lives on.
  CASE
    WHEN a."account_type" IN ('gateway_cash', 'provider_dues')
      THEN coalesce(sum(CASE WHEN e."direction" = 'debit' THEN e."amount_paise" ELSE -e."amount_paise" END), 0)
    ELSE coalesce(sum(CASE WHEN e."direction" = 'credit' THEN e."amount_paise" ELSE -e."amount_paise" END), 0)
  END::BIGINT AS balance_paise
FROM "accounts" a
LEFT JOIN "ledger_entries" e ON e."account_id" = a."id"
GROUP BY a."id", a."account_type", a."owner_type", a."owner_id";

CREATE OR REPLACE VIEW "provider_balances" AS
SELECT
  b.owner_id AS provider_id,
  coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'provider_payable'), 0)::BIGINT AS payable_paise,
  coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'provider_dues'), 0)::BIGINT    AS dues_paise,
  (
    coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'provider_payable'), 0)
    - coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'provider_dues'), 0)
  )::BIGINT AS net_paise
FROM "account_balances" b
WHERE b.owner_type = 'provider'
GROUP BY b.owner_id;

CREATE OR REPLACE VIEW "platform_revenue_view" AS
SELECT
  coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'platform_revenue'), 0)::BIGINT AS revenue_paise,
  coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'gateway_cash'), 0)::BIGINT     AS gateway_cash_paise,
  coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'provider_payable'), 0)::BIGINT AS owed_to_providers_paise,
  coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'provider_dues'), 0)::BIGINT    AS owed_by_providers_paise,
  coalesce(sum(b.balance_paise) FILTER (WHERE b.account_type = 'refunds_payable'), 0)::BIGINT  AS refunds_pending_paise
FROM "account_balances" b;

-- ---------------------------------------------------------------------------
-- Payout batch totals
-- ---------------------------------------------------------------------------
--
-- A batch header that disagrees with its own lines is how a payout run quietly
-- pays the wrong amount. Deferred, because the header is written before the
-- lines it describes.
CREATE OR REPLACE FUNCTION payout_batch_totals_match() RETURNS trigger AS $$
DECLARE
  line_total BIGINT;
  line_count INT;
BEGIN
  SELECT coalesce(sum("amount_paise"), 0), count(*)
  INTO line_total, line_count
  FROM "payouts" WHERE "batch_id" = NEW."id";

  IF line_total <> NEW."total_paise" OR line_count <> NEW."payout_count" THEN
    RAISE EXCEPTION
      'payout batch % header says %p over % payouts but its lines say %p over %',
      NEW."id", NEW."total_paise", NEW."payout_count", line_total, line_count
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- ===========================================================================
-- REVIEWS ARE APPEND-ONLY, EXCEPT FOR MODERATION
--
-- A review is somebody's account of what happened to them. Editing it after the
-- fact — by us, by the author, by anyone — would make every other review
-- unreliable, because a reader could no longer tell which ones had been touched.
--
-- The single permitted change is `status`, so ops can hide something abusive.
-- Hidden reviews are excluded from every aggregate on the next recompute; the
-- row survives, because deleting evidence of a moderation decision is its own
-- kind of dishonesty.
-- ===========================================================================
CREATE OR REPLACE FUNCTION reviews_moderation_only() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF coalesce(current_setting('fixbridge.allow_kyc_purge', true), '') = 'on' THEN
      RETURN OLD;
    END IF;

    RAISE EXCEPTION 'reviews are append-only: DELETE is not permitted (id=%)', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW.id = OLD.id
     AND NEW.booking_id = OLD.booking_id
     AND NEW.direction = OLD.direction
     AND NEW.author_user_id = OLD.author_user_id
     AND NEW.subject_user_id = OLD.subject_user_id
     AND NEW.stars = OLD.stars
     AND NEW.tags IS NOT DISTINCT FROM OLD.tags
     AND NEW.text IS NOT DISTINCT FROM OLD.text
     AND NEW.created_at = OLD.created_at
  THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION
    'review % is immutable: only status may change (moderation)', OLD.id
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "reviews_moderation_only_update"
  BEFORE UPDATE ON "reviews"
  FOR EACH ROW EXECUTE FUNCTION reviews_moderation_only();

CREATE TRIGGER "reviews_no_delete"
  BEFORE DELETE ON "reviews"
  FOR EACH ROW EXECUTE FUNCTION reviews_moderation_only();

-- ===========================================================================
-- SNAPSHOTS ARE APPEND-ONLY
--
-- A snapshot is the answer to "why was my score 62 last Tuesday". Rewriting one
-- would destroy the only record of what the engine actually did, which is the
-- whole reason the table exists rather than a single mutable column.
--
-- A recompute writes a new row. It never edits the last one.
-- ===========================================================================
CREATE OR REPLACE FUNCTION trust_snapshots_append_only() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' AND coalesce(current_setting('fixbridge.allow_kyc_purge', true), '') = 'on' THEN
    RETURN OLD;
  END IF;

  RAISE EXCEPTION
    'trust_score_snapshots is append-only: % is not permitted', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trust_score_snapshots_no_update"
  BEFORE UPDATE ON "trust_score_snapshots"
  FOR EACH ROW EXECUTE FUNCTION trust_snapshots_append_only();

CREATE TRIGGER "trust_score_snapshots_no_delete"
  BEFORE DELETE ON "trust_score_snapshots"
  FOR EACH ROW EXECUTE FUNCTION trust_snapshots_append_only();


-- CreateIndex
--
-- The pending-approval queue: everybody a human has not yet waved through.
-- Partial, because the queue is the small set and the approved are the many.
CREATE INDEX "provider_profiles_pending_entry_idx"
  ON "provider_profiles" ("city_id", "created_at")
  WHERE "entry_approved_at" IS NULL;

-- ---------------------------------------------------------------------------
-- Append-only
-- ---------------------------------------------------------------------------
--
-- An audit log that can be edited is not an audit log. UPDATE is refused
-- outright **except** the one narrow case the SET NULL above requires: severing
-- `actor_user_id` when the actor exercises erasure. Without that exception the
-- foreign key could never fire and DPDP erasure of an ops user would be
-- impossible — the same trap `ledger_journals` fell into in Phase 8.
--
-- DELETE is refused unless the purge flag is set, which only
-- `set_config('fixbridge.allow_kyc_purge', 'on', true)` inside a deliberate
-- erasure transaction does.
CREATE OR REPLACE FUNCTION audit_logs_append_only() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF coalesce(current_setting('fixbridge.allow_kyc_purge', true), '') = 'on' THEN
      RETURN OLD;
    END IF;

    RAISE EXCEPTION 'audit_logs is append-only: DELETE is not permitted (id=%)', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- The only permitted UPDATE: anonymising the actor. Everything else about the
  -- row — what was done, to whom, with what substance — must be identical.
  IF NEW.id = OLD.id
     AND NEW.action = OLD.action
     AND NEW.target_type = OLD.target_type
     AND NEW.target_id IS NOT DISTINCT FROM OLD.target_id
     AND NEW.payload::text = OLD.payload::text
     AND NEW.created_at = OLD.created_at
     AND NEW.actor_user_id IS NULL
     AND OLD.actor_user_id IS NOT NULL
  THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'audit_logs is append-only: row % may not be modified', OLD.id
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_logs_append_only
  BEFORE UPDATE OR DELETE ON "audit_logs"
  FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only();


-- The two staff-password triggers that used to live here are gone.
--
-- They guarded users.password_hash: only ops/admin could hold one, and losing
-- the role wiped it. Staff no longer live in `users` at all -- they are
-- `admin_users` rows with email + password -- so both triggers guarded a
-- column that no longer exists.


-- Case-insensitive uniqueness, enforced by the database.
--
-- The service lower-cases before writing, but `Admin@x.com` and `admin@x.com`
-- must not be able to become two accounts even if some future code path
-- forgets to normalise. A plain unique index on the column would treat them as
-- distinct; this one does not.
CREATE UNIQUE INDEX "admin_users_email_lower_key" ON "admin_users" (LOWER("email"));


-- ===========================================================================
-- CHECK constraints.
-- ===========================================================================
--
-- Prisma does not emit CHECK constraints from the datamodel, so these are
-- carried over verbatim from the 14 original migrations. They are the
-- invariants the application must never be trusted to remember on its own:
-- money is non-negative, stars are 1-5, a booking ends after it starts, a
-- quotation total equals the sum of its lines.
--
-- The one original NOT carried over is the GiST exclusion constraint
-- slots_no_double_booking, which needed btree_gist; its replacement is the
-- partial unique index below.

-- from 20260815112721_add_categories_customers_providers
-- Availability windows: valid weekday, minute-of-day range, and no overnight
-- windows (end must be strictly after start) — the documented v1 limitation.
ALTER TABLE "provider_availability_templates"
  ADD CONSTRAINT "provider_availability_day_of_week_check" CHECK ("day_of_week" BETWEEN 0 AND 6),
  ADD CONSTRAINT "provider_availability_start_minute_check" CHECK ("start_minute" BETWEEN 0 AND 1439),
  ADD CONSTRAINT "provider_availability_end_minute_check" CHECK ("end_minute" BETWEEN 1 AND 1440),
  ADD CONSTRAINT "provider_availability_range_check" CHECK ("end_minute" > "start_minute");

-- from 20260815112721_add_categories_customers_providers
-- Service radius stays inside the documented 1–25 km band.
ALTER TABLE "provider_profiles"
  ADD CONSTRAINT "provider_profiles_service_radius_check" CHECK ("service_radius_km" BETWEEN 1 AND 25),
  ADD CONSTRAINT "provider_profiles_completeness_check" CHECK ("completeness_score" BETWEEN 0 AND 100),
  ADD CONSTRAINT "provider_profiles_years_experience_check" CHECK ("years_experience" IS NULL OR "years_experience" BETWEEN 0 AND 70);

-- from 20260815112721_add_categories_customers_providers
-- Money is always a non-negative integer number of paise, and is present for
-- exactly the price types that carry an amount.
ALTER TABLE "provider_price_cards"
  ADD CONSTRAINT "provider_price_cards_amount_sign_check" CHECK ("amount_paise" IS NULL OR "amount_paise" >= 0),
  ADD CONSTRAINT "provider_price_cards_amount_presence_check" CHECK (
    ("price_type" = 'inspection_based' AND "amount_paise" IS NULL)
    OR ("price_type" <> 'inspection_based' AND "amount_paise" IS NOT NULL)
  );

-- from 20260815140000_add_verification_and_storage
ALTER TABLE "provider_documents"
  ADD CONSTRAINT "provider_documents_size_bytes_check" CHECK ("size_bytes" >= 0),
  ADD CONSTRAINT "provider_documents_uploaded_at_check" CHECK (
    ("status" = 'uploaded' AND "uploaded_at" IS NOT NULL)
    OR ("status" = 'awaiting_upload' AND "uploaded_at" IS NULL)
  );

-- from 20260815140000_add_verification_and_storage
-- Levels are 0 identity, 1 background, 2 skill, 3 references. Nothing else.
ALTER TABLE "verification_cases"
  ADD CONSTRAINT "verification_cases_level_check" CHECK ("level" BETWEEN 0 AND 3),
  ADD CONSTRAINT "verification_cases_closed_at_check" CHECK (
    ("status" IN ('passed', 'failed') AND "closed_at" IS NOT NULL)
    OR ("status" NOT IN ('passed', 'failed') AND "closed_at" IS NULL)
  );

-- from 20260815140000_add_verification_and_storage
-- A human action must name the human; a system action must not invent one.
ALTER TABLE "verification_events"
  ADD CONSTRAINT "verification_events_actor_check" CHECK (
    ("actor_type" = 'system' AND "actor_user_id" IS NULL)
    OR ("actor_type" <> 'system' AND "actor_user_id" IS NOT NULL)
  );

-- from 20260815140000_add_verification_and_storage
ALTER TABLE "provider_verification_summaries"
  ADD CONSTRAINT "provider_verification_summaries_levels_check" CHECK (
    "levels_passed" <@ ARRAY[0, 1, 2, 3]
    AND int_array_is_distinct("levels_passed")
  ),
  ADD CONSTRAINT "provider_verification_summaries_badge_since_check" CHECK (
    ("badge" = 'NONE' AND "badge_since" IS NULL)
    OR ("badge" <> 'NONE' AND "badge_since" IS NOT NULL)
  );

-- from 20260815170000_add_hinglish_synonyms
-- Weight is a multiplier on a match, so zero or negative makes no sense.
ALTER TABLE "hinglish_synonyms"
  ADD CONSTRAINT "hinglish_synonyms_weight_check" CHECK ("weight" > 0);

-- from 20260815200000_add_slots_bookings_outbox
ALTER TABLE "slots"
  ADD CONSTRAINT "slots_time_order_check" CHECK ("ends_at" > "starts_at"),
  -- A booked slot must name its booking; an open one must not.
  ADD CONSTRAINT "slots_booking_link_check" CHECK (
    ("status" IN ('held', 'booked') AND "booking_id" IS NOT NULL)
    OR ("status" IN ('open', 'blocked') AND "booking_id" IS NULL)
  );

-- from 20260815200000_add_slots_bookings_outbox
ALTER TABLE "bookings"
  ADD CONSTRAINT "bookings_time_order_check" CHECK ("ends_at" > "starts_at"),
  ADD CONSTRAINT "bookings_visit_fee_check" CHECK ("visit_fee_paise" >= 0);

-- from 20260815200000_add_slots_bookings_outbox
ALTER TABLE "booking_events"
  ADD CONSTRAINT "booking_events_actor_check" CHECK (
    ("actor_type" = 'system' AND "actor_user_id" IS NULL)
    OR ("actor_type" <> 'system' AND "actor_user_id" IS NOT NULL)
  );

-- from 20260815200000_add_slots_bookings_outbox
ALTER TABLE "outbox"
  ADD CONSTRAINT "outbox_attempts_check" CHECK ("attempts" >= 0);

-- from 20260815200000_add_slots_bookings_outbox
ALTER TABLE "provider_stats"
  ADD CONSTRAINT "provider_stats_counts_check" CHECK (
    "accepted_count" >= 0 AND "rejected_count" >= 0
    AND "expired_count" >= 0 AND "cancelled_by_provider_count" >= 0
  ),
  ADD CONSTRAINT "provider_stats_rate_check" CHECK (
    "acceptance_rate" IS NULL OR ("acceptance_rate" >= 0 AND "acceptance_rate" <= 1)
  );

-- from 20260816120000_add_quotations_and_fees
ALTER TABLE "fee_config"
  ADD CONSTRAINT "fee_config_amount_check" CHECK ("visit_fee_paise" >= 0);

-- from 20260816120000_add_quotations_and_fees
-- Totals are derived, so they are checked rather than trusted. A service bug
-- that miscomputes a total cannot reach a customer's screen.
ALTER TABLE "quotations"
  ADD CONSTRAINT "quotations_version_check" CHECK ("version" >= 1),
  ADD CONSTRAINT "quotations_labour_check" CHECK ("labour_paise" >= 0),
  ADD CONSTRAINT "quotations_parts_check" CHECK ("parts_total_paise" >= 0),
  ADD CONSTRAINT "quotations_total_check" CHECK ("total_paise" = "labour_paise" + "parts_total_paise"),
  -- A pure-labour quote is legal. An empty one is not: "₹0, please approve"
  -- is not a price, it is a bug.
  ADD CONSTRAINT "quotations_nonempty_check" CHECK ("total_paise" > 0),
  -- `sent` is the only live state, and the only one without a decision time.
  ADD CONSTRAINT "quotations_decided_check" CHECK (
    ("status" = 'sent' AND "decided_at" IS NULL)
    OR ("status" <> 'sent' AND "decided_at" IS NOT NULL)
  ),
  -- A reason only makes sense on a rejection.
  ADD CONSTRAINT "quotations_decision_note_check" CHECK (
    "decision_note" IS NULL OR "status" = 'rejected'
  );

-- from 20260816120000_add_quotations_and_fees
ALTER TABLE "quotation_items"
  ADD CONSTRAINT "quotation_items_qty_check" CHECK ("qty" >= 1),
  ADD CONSTRAINT "quotation_items_unit_check" CHECK ("unit_paise" > 0),
  ADD CONSTRAINT "quotation_items_line_total_check" CHECK ("line_total_paise" = "qty" * "unit_paise"),
  ADD CONSTRAINT "quotation_items_description_check" CHECK (length(btrim("description")) > 0);

-- from 20260816180000_snapshot_price_card_on_booking
-- Deliberately NOT tied to `price_card_id` being present.
--
-- That column is `ON DELETE SET NULL`, so a coupling CHECK would make deleting a
-- price card fail against every historical booking — and the whole point of a
-- snapshot is that it survives the thing it copied.
ALTER TABLE "bookings"
  ADD CONSTRAINT "bookings_price_card_amount_check" CHECK (
    "price_card_amount_paise" IS NULL OR "price_card_amount_paise" >= 0
  );

-- from 20260816190000_add_ledger_payments_payouts
-- A platform account has no owner; anybody else's must have one.
ALTER TABLE "accounts"
  ADD CONSTRAINT "accounts_owner_check" CHECK (
    ("owner_type" = 'platform' AND "owner_id" IS NULL)
    OR ("owner_type" <> 'platform' AND "owner_id" IS NOT NULL)
  );

-- from 20260816190000_add_ledger_payments_payouts
-- A zero-value entry is not a movement of money; a negative one is a direction
-- written the wrong way round. Both are bugs, and both are refused.
ALTER TABLE "ledger_entries"
  ADD CONSTRAINT "ledger_entries_amount_check" CHECK ("amount_paise" > 0);

-- from 20260816190000_add_ledger_payments_payouts
ALTER TABLE "commission_config"
  ADD CONSTRAINT "commission_config_rate_check" CHECK ("rate_bps" >= 0 AND "rate_bps" <= 10000);

-- from 20260816190000_add_ledger_payments_payouts
ALTER TABLE "payments"
  ADD CONSTRAINT "payments_amount_check" CHECK ("amount_paise" > 0),
  ADD CONSTRAINT "payments_commission_check" CHECK (
    "commission_bps_snapshot" >= 0 AND "commission_bps_snapshot" <= 10000
  ),
  -- Cash has no gateway, no order and no webhook. Saying so in the schema stops
  -- three columns from being permanently null with nothing explaining why.
  ADD CONSTRAINT "payments_rail_check" CHECK (
    ("method" = 'online' AND "gateway" IS NOT NULL AND "gateway_order_id" IS NOT NULL)
    OR ("method" = 'cash' AND "gateway" IS NULL AND "gateway_order_id" IS NULL
        AND "gateway_payment_id" IS NULL AND "checkout_verified_at" IS NULL)
  ),
  ADD CONSTRAINT "payments_captured_check" CHECK (
    ("status" IN ('captured', 'refunded', 'partially_refunded') AND "captured_at" IS NOT NULL)
    OR ("status" IN ('created', 'failed') AND "captured_at" IS NULL)
  );

-- from 20260816190000_add_ledger_payments_payouts
ALTER TABLE "refunds"
  ADD CONSTRAINT "refunds_amount_check" CHECK ("amount_paise" > 0);

-- from 20260816190000_add_ledger_payments_payouts
ALTER TABLE "payouts"
  ADD CONSTRAINT "payouts_amount_check" CHECK ("amount_paise" > 0),
  ADD CONSTRAINT "payouts_paid_check" CHECK (
    ("status" = 'paid' AND "paid_at" IS NOT NULL AND "utr_ref" IS NOT NULL)
    OR ("status" <> 'paid')
  );

-- from 20260816190000_add_ledger_payments_payouts
ALTER TABLE "payout_batches"
  ADD CONSTRAINT "payout_batches_totals_check" CHECK ("total_paise" >= 0 AND "payout_count" >= 0);

-- from 20260816220000_add_reviews_complaints_trust
-- Suspended or not, coherently. A profile cannot carry an end date with no
-- reason, or a reason with no end date — either would leave ops guessing.
ALTER TABLE "provider_profiles"
  ADD CONSTRAINT "provider_profiles_suspension_check" CHECK (
    ("suspended_until" IS NULL AND "suspended_at" IS NULL AND "suspension_reason" IS NULL)
    OR ("suspended_until" IS NOT NULL AND "suspended_at" IS NOT NULL AND "suspension_reason" IS NOT NULL)
  );

-- from 20260816220000_add_reviews_complaints_trust
ALTER TABLE "provider_stats"
  ADD CONSTRAINT "provider_stats_stars_check" CHECK (
    "avg_stars" IS NULL OR ("avg_stars" >= 1 AND "avg_stars" <= 5)
  ),
  -- Null means "no data yet", which the ranking treats as neutral. Zero means
  -- "we scored them and they scored zero". Keeping both possible, and distinct,
  -- is the whole reason this column is nullable.
  ADD CONSTRAINT "provider_stats_trust_check" CHECK (
    "trust_score" IS NULL OR ("trust_score" >= 0 AND "trust_score" <= 100)
  ),
  ADD CONSTRAINT "provider_stats_counts_nonneg_check" CHECK (
    "review_count" >= 0 AND "settled_jobs_count" >= 0
    AND "complaints_minor_count" >= 0 AND "complaints_major_count" >= 0
    AND "complaints_severe_count" >= 0
  );

-- from 20260816220000_add_reviews_complaints_trust
ALTER TABLE "reviews"
  ADD CONSTRAINT "reviews_stars_check" CHECK ("stars" >= 1 AND "stars" <= 5),
  -- Nobody rates themselves.
  ADD CONSTRAINT "reviews_parties_check" CHECK ("author_user_id" <> "subject_user_id"),
  -- Five tags is already more than anybody reads on a phone.
  ADD CONSTRAINT "reviews_tags_check" CHECK (array_length("tags", 1) IS NULL OR array_length("tags", 1) <= 5);

-- from 20260816220000_add_reviews_complaints_trust
ALTER TABLE "complaints"
  ADD CONSTRAINT "complaints_parties_check" CHECK ("raised_by_user_id" <> "against_user_id"),
  -- A resolution needs a note and a severity; a dismissal needs a note and
  -- **no** severity. An accusation that did not stand up is not a record
  -- against anybody, and giving it a severity would make it one.
  ADD CONSTRAINT "complaints_resolution_check" CHECK (
    ("status" = 'resolved' AND "resolution_note" IS NOT NULL AND "severity_on_resolution" IS NOT NULL AND "resolved_at" IS NOT NULL)
    OR ("status" = 'dismissed' AND "resolution_note" IS NOT NULL AND "severity_on_resolution" IS NULL AND "resolved_at" IS NOT NULL)
    OR ("status" IN ('open', 'in_review') AND "severity_on_resolution" IS NULL AND "resolved_at" IS NULL)
  );

-- from 20260816220000_add_reviews_complaints_trust
ALTER TABLE "trust_score_snapshots"
  ADD CONSTRAINT "trust_score_snapshots_score_check" CHECK ("score" >= 0 AND "score" <= 100);

-- Search covering indexes.
--
-- Both exist so the search join does not have to visit the heap: the query
-- filters candidates by category and by badge, and having the provider id in
-- the index itself lets Postgres answer from the index alone.

CREATE INDEX "provider_skills_category_provider_idx"
  ON "provider_skills" ("category_id", "provider_id");

CREATE INDEX "provider_verification_summaries_badge_provider_idx"
  ON "provider_verification_summaries" ("badge", "provider_id");

-- ===========================================================================
-- Staff refresh tokens.
-- ===========================================================================
--
-- Separate from refresh_tokens because that table's user_id has a foreign key
-- to users, and staff are admin_users rows. Sharing one table would mean
-- dropping that foreign key for every customer too, which would let an
-- orphaned token outlive the account it belonged to.

CREATE TABLE "admin_refresh_tokens" (
    "id" UUID NOT NULL,
    "admin_id" UUID NOT NULL,
    "token_hash" CHAR(64) NOT NULL,
    "device_id" VARCHAR(128) NOT NULL,
    "device_info" VARCHAR(512),
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "revoked_at" TIMESTAMPTZ(3),
    "replaced_by_token_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "admin_refresh_tokens_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "admin_refresh_tokens_token_hash_key" ON "admin_refresh_tokens"("token_hash");
CREATE UNIQUE INDEX "admin_refresh_tokens_replaced_by_token_id_key" ON "admin_refresh_tokens"("replaced_by_token_id");
CREATE INDEX "admin_refresh_tokens_admin_id_device_id_idx" ON "admin_refresh_tokens"("admin_id", "device_id");
CREATE INDEX "admin_refresh_tokens_expires_at_idx" ON "admin_refresh_tokens"("expires_at");

ALTER TABLE "admin_refresh_tokens"
    ADD CONSTRAINT "admin_refresh_tokens_admin_id_fkey"
    FOREIGN KEY ("admin_id") REFERENCES "admin_users"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "admin_refresh_tokens"
    ADD CONSTRAINT "admin_refresh_tokens_replaced_by_token_id_fkey"
    FOREIGN KEY ("replaced_by_token_id") REFERENCES "admin_refresh_tokens"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

-- ===========================================================================
-- Scope uniqueness, with NULLS NOT DISTINCT.
-- ===========================================================================
--
-- All three depend on Postgres 15+ NULLS NOT DISTINCT, and that is the entire
-- point of them. Under the ordinary rule two NULLs count as different, so a
-- plain unique index would allow exactly the duplicates these exist to forbid:
-- a second platform account silently splitting the platform's income, or two
-- conflicting city-default configs for the same date that the resolver would
-- then pick between arbitrarily.

-- One account per (type, owner). Platform accounts have a NULL owner.
CREATE UNIQUE INDEX "accounts_scope_idx"
  ON "accounts" ("account_type", "owner_type", "owner_id") NULLS NOT DISTINCT;

-- One fee per scope per effective date; category_id is NULL for a city default.
CREATE UNIQUE INDEX "fee_config_scope_idx"
  ON "fee_config" ("city_id", "category_id", "effective_from") NULLS NOT DISTINCT;

-- Same shape as fee_config: one rate per scope per effective date.
CREATE UNIQUE INDEX "commission_config_scope_idx"
  ON "commission_config" ("city_id", "category_id", "effective_from") NULLS NOT DISTINCT;

-- ===========================================================================
-- The double-booking wall.
-- ===========================================================================
--
-- Two customers can tap "book" on the same slot in the same millisecond. No
-- amount of application care can prevent that — a check-then-insert is a race
-- however carefully written, and a Redis lock disappears the moment Redis
-- blinks. So the guarantee lives in the database.
--
-- Previously an `EXCLUDE USING gist` over a derived tstzrange, which refused any
-- *overlapping* pair. That needs btree_gist, which this host does not have.
--
-- This partial unique index refuses two live slots sharing a provider and a
-- start time. See the header note for why that is equivalent given grid-aligned
-- slot generation, and what it stops covering if that ever changes.
--
-- The WHERE clause matters: 'open' and 'blocked' slots are allowed to coexist,
-- which is what makes template regeneration possible.
CREATE UNIQUE INDEX "slots_no_double_booking"
  ON "slots" ("provider_id", "starts_at")
  WHERE "status" IN ('held', 'booked');

-- The indexes the bounding-box pre-filter relies on.
--
-- These are what replace the two GiST spatial indexes. The box is a plain range
-- predicate, so a B-tree serves it — which is the whole reason search stays fast
-- without PostGIS.
--
-- `city_id` leads the provider index because search always filters on it with
-- equality, and an equality column first is what lets the range columns after it
-- be used. Partial, because a provider who has not set a base location can never
-- match a radius query and does not belong in the index.
CREATE INDEX "provider_profiles_city_base_latlng_idx"
  ON "provider_profiles" ("city_id", "base_lat", "base_lng")
  WHERE "base_lat" IS NOT NULL AND "base_lng" IS NOT NULL;

CREATE INDEX "addresses_lat_lng_idx" ON "addresses" ("lat", "lng");
